### ISSUE TITLE
SimpleMixer crashes TD after giving CHOP OSC warning on startup

### ISSUE THREAD

**Issue by popsure** [Richard-Burns/SimpleMixer#42]
Basically it runs fullscreen on startup, you can't interact with any of the elements, there is a warning message you can click ok on complaining about expressions in OSC CHOPs, which after clicking ok freezes TD. I think the issue is somewhere in UIKit.

64-Bit Build 2019.10700 Windows 10

**Comment by Richard-Burns** [comment]
This is due to touchdesigner upgrading the OSC In CHOP on Experimental builds and breaking it for upgraded projects. SimpleMixers master branch will only support official for now. I'll shortly upgrade the Experimental branch to support the latest builds and will close this issue once that is done. If you want to fix it yourself for now just downgrade to stable, delete the OSC In CHOPs inside the ui kit and then re-upgrade and re-create the CHOP with the same name. OSC In settings have changed so there'll be a new ui setup for those shortly. I'll close this issue once we're good to go.

**Comment by popsure** [comment]
Thanks for the support! Figured it was due to the experimental version so downgraded to make it work. Putting CrashAutoSave. in front of the filename is also a trick you can use to open the project without anything cooking.
