### ISSUE TITLE
Performance after starting simplemixer

### ISSUE THREAD

**Issue by osterstone** [Richard-Burns/SimpleMixer#53]
When starting simplemixer fresh and going into PerfMode I have an FPS of 2.
If I disable cooking the container simplemixer the FPS goes of course up.
Enabling cooking this container again gives me a reasonable FPS rate of 45 to 48. And this stays as long as I dont leave
TD.

I downloaded the latest version of simplemixer.
I am working on a acer predator helios 300 with an GeForce GTX 1660TI.
TD Version 2020.46540
Win10

**Comment by osterstone** [comment]
Solved: base_tox.tox is missing recreate call on start

**Comment by dithid** [comment]
I juste did a fast check on it, having the same issue. 
The issue is coming from the replicator inside the base_tox, in the callback the line c.par.reinitnet.pulse() is somehow messing up when starting.
You can delete this line and you should not have this problem anymore but then when you add a tox to your folder you have to relaunch the project in order to load it.

**Comment by osterstone** [comment]
Thank you. Confirmed: If I delete that line, the issue is gone.
No idea why this happens .

**Comment by aspitarl** [comment]
I had the same issue with the same fix on one of my computers. But everything started with 60 FPS fine on two other computers. Interestingly the one that did have issues was my more powerful desktop, and the others are two laptops, but I doubt this is a hardware capability issue.
